# Generated by Django 4.0.1 on 2022-02-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_products_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InvoiceNo', models.BigIntegerField(verbose_name='InvoiceNo')),
                ('StockCode', models.IntegerField(verbose_name='StockCode')),
                ('Description', models.CharField(max_length=255, verbose_name='Description')),
                ('Quantity', models.IntegerField(verbose_name='Quantity')),
                ('InvoiceDate', models.DateTimeField(auto_now=True, verbose_name='InvoiceDate')),
                ('UnitPrice', models.FloatField(max_length=255, verbose_name='UnitPrice')),
                ('CostumerId', models.IntegerField(verbose_name='CostumerId')),
                ('Country', models.CharField(max_length=255, verbose_name='Country')),
            ],
        ),
    ]
