# Generated by Django 4.0.1 on 2022-02-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='InvoiceNo',
            field=models.CharField(max_length=135, verbose_name='InvoiceNo'),
        ),
        migrations.AlterField(
            model_name='item',
            name='StockCode',
            field=models.CharField(max_length=135, verbose_name='StockCode'),
        ),
    ]
