# Generated by Django 4.0.1 on 2022-02-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_item_invoiceno_alter_item_stockcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='StockCode',
            field=models.CharField(max_length=135, null=True, verbose_name='StockCode'),
        ),
    ]
