# Generated by Django 4.0.1 on 2022-03-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_customer_alter_products_options_orderplaced_carts'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=150)),
                ('lname', models.CharField(max_length=150)),
                ('uname', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('adderess', models.CharField(max_length=200)),
                ('payment', models.CharField(choices=[('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('Khalti', 'Khalti')], default='Payment', max_length=50)),
                ('cname', models.CharField(max_length=120)),
                ('cnum', models.IntegerField(default=0)),
                ('exp', models.IntegerField(default=0)),
                ('CVV', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='carts',
            options={'verbose_name_plural': 'cart'},
        ),
        migrations.AlterModelOptions(
            name='orderplaced',
            options={'verbose_name_plural': 'Orders'},
        ),
    ]
